name: SPA C++ Linting (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 09,23 * * *"

env:
  BUILD_TYPE: Debug

jobs:
  lint:
    name: Lint C++ Code
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install cpplint
      run: pip install cpplint

    - name: Run cpplint and Generate Results File
      run: |
         $resultsPath = Join-Path ${{ github.workspace }} "cpplint-results.txt"
         Get-ChildItem ./Team19/Code19/src/spa -Recurse -Include *.cpp, *.h | Foreach-Object {
          $output = cpplint $_.FullName | Out-String
          Add-Content -Path $resultsPath -Value $output
         }
      shell: powershell
      continue-on-error: true

    - name: Upload cpplint Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cpplint-results
        path: ${{ github.workspace }}/cpplint-results.txt