name: Unit Tests (MacOS)

# ai-gen (copilot, 5, e)
# prompt: used copilot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

env:
    BUILD_TYPE: Debug
    CMAKE_DIR: ${{ github.workspace }}/Team19/Code19
    BUILD_DIR: ${{ github.workspace }}/Team19/Code19/build
    TEST_DIR: ${{ github.workspace }}/Team19/Code19/build/src/unit_testing

jobs:
  build_unit_mac:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        cc-compilers: [clang]
        cxx-compilers: [clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake ${{ env.CMAKE_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      # Build CMake Project and Unit Testing
      - name: Build Project
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: |
            cmake --build . --config ${{ env.BUILD_TYPE }} -j 4
            cmake --build . --target unit_testing --config ${{ env.BUILD_TYPE }} -j 4

      - name: Run Unit Tests
        working-directory: ${{ env.TEST_DIR }}
        run: |
            ${{ env.TEST_DIR }}/unit_testing

      - name: Cleanup Directory
        if: always()
        run: |
          shopt -s dotglob
          rm -rf ./Team19/Code19/build || true

# ai-gen end