name: Build + Integration Tests (MacOS)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

env:
    BUILD_TYPE: Debug
    CMAKE_DIR: ${{ github.workspace }}/Team19/Code19
    BUILD_DIR: ${{ github.workspace }}/Team19/Code19/build
    TEST_DIR: ${{ github.workspace }}/Team19/Code19/build/src/integration_testing

jobs:
  build_unit_mac:
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build-type: [Debug]
        cc-compilers: [clang]
        cxx-compilers: [clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake ${{ env.CMAKE_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build Project
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        env:
          CC: ${{ matrix.cc-compilers }}
          CXX: ${{ matrix.cxx-compilers }}
        run: | 
            cmake --build . --config ${{ matrix.build-type }} -j 4
            cmake --build . --target integration_testing --config ${BUILD_TYPE} -j 4

      - name: Run Unit Tests
        working-directory: ${{ env.TEST_DIR }}
        run: |
            ${{ env.TEST_DIR }}/integration_testing

      - name: Cleanup Directory
        if: always()
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
