name: Autotester (MacOS)

# ai-gen start (copilot, 5, e)
# prompt: used copilot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

env:
    BUILD_TYPE: Debug
    CMAKE_DIR: ${{ github.workspace }}/Team19/Code19
    BUILD_DIR: ${{ github.workspace }}/Team19/Code19/build
    TEST_DIR: ${{ github.workspace }}/Team19/Code19/build/src/autotester
    AUTOTESTER_M1_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m1
    AUTOTESTER_M2_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m2

jobs:
  build_autotester_mac:
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        cc-compilers: [clang]
        cxx-compilers: [clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake ${{ env.CMAKE_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      # Build projects on MacOS and build Autotester
      - name: Build Project
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: |
            cmake --build . --config ${{ env.BUILD_TYPE }} -j 4
            cmake --build . --target autotester --config ${{ env.BUILD_TYPE }} -j 4
      
      # Recursively find all source files and run autotester on them for Milestone 1
      - name: Run Autotester on Milestone 1
        shell: bash
        working-directory: ${{ env.AUTOTESTER_M1_DIR }}
        run: |
            mkdir -p logs outputs
            echo "[System Test] Running all tests for Milestone 1"
            EXIT_CODE="0"

            for file in source/*_source.txt; do
                # shellcheck disable=SC2001
                test_name=$(echo "$file" | sed 's|.*/\(.*\)_source\.txt$|\1|') # regex generated with aid of ChatGPT
                echo "[System Test] Running Test: $test_name"
                
                # Run the test and capture the time
                TIME_FILE="logs/time_${test_name}.txt"
                (time ${{ env.TEST_DIR }}/autotester "$file" queries/"$test_name"_queries.txt outputs/"$test_name"_output.xml > logs/log_"$test_name".txt) 2>&1 | tee "$TIME_FILE"

                # Extract the real time, convert to milliseconds
                real_seconds=$(grep real "$TIME_FILE" | awk '{print $2}' | sed -E 's/([0-9]+)m([0-9.]+)s/\1*60+\2/' | bc)
                milliseconds=$(echo "$real_seconds*1000/1" | bc)

                echo "[System Test] Test $test_name completed in $milliseconds milliseconds"


                if [ "$?" != 0 ]; then
                echo "[System Test] Test $test_name has failed"
                EXIT_CODE="1"
                else
                echo "[System Test] Test $test_name succeed"
                head -1 logs/log_"$test_name".txt
                FILENAME=outputs/"$test_name"_output.xml
                QUERIES=$(grep -o '</query>' "$FILENAME" | wc -l)
                PASSES=$(grep -o '<passed/>' "$FILENAME" | wc -l)
                FAILS=$(grep -c '</failed>' "$FILENAME" || echo "0")
                EXCEPTIONS=$(grep -c '<exception/>' "$FILENAME" || echo "0")
                echo "[System Test] Queries: $QUERIES; Passes: $PASSES; Fails: $FAILS; EXCEPTIONS: $EXCEPTIONS"
                if [ "$QUERIES" != "$PASSES" ]; then
                    echo "[Alert!] Some system tests have failed. Please try again!"
                    EXIT_CODE="2"
                fi
                fi
            done

            exit $EXIT_CODE

      # Recursively find all source files and run autotester on them for Milestone 2
      - name: Run Autotester on Milestone 2
        shell: bash
        working-directory: ${{ env.AUTOTESTER_M2_DIR }}
        run: |
            mkdir -p logs outputs
            echo "[System Test] Running all tests for Milestone 1"
            EXIT_CODE="0"

            for file in source/*_source.txt; do
                # shellcheck disable=SC2001
                test_name=$(echo "$file" | sed 's|.*/\(.*\)_source\.txt$|\1|') # regex generated with aid of ChatGPT
                echo "[System Test] Running Test: $test_name"
                # Start time measurement in milliseconds
                # Run the test and capture the time
                TIME_FILE="logs/time_${test_name}.txt"
                (time ${{ env.TEST_DIR }}/autotester "$file" queries/"$test_name"_queries.txt outputs/"$test_name"_output.xml > logs/log_"$test_name".txt) 2>&1 | tee "$TIME_FILE"

                # Extract the real time, convert to milliseconds
                real_seconds=$(grep real "$TIME_FILE" | awk '{print $2}' | sed -E 's/([0-9]+)m([0-9.]+)s/\1*60+\2/' | bc)
                milliseconds=$(echo "$real_seconds*1000/1" | bc)

                echo "[System Test] Test $test_name completed in $milliseconds milliseconds"

                if [ "$?" != 0 ]; then
                echo "[System Test] Test $test_name has failed"
                EXIT_CODE="1"
                else
                echo "[System Test] Test $test_name succeed"
                head -1 logs/log_"$test_name".txt
                FILENAME=outputs/"$test_name"_output.xml
                QUERIES=$(grep -o '</query>' "$FILENAME" | wc -l)
                PASSES=$(grep -o '<passed/>' "$FILENAME" | wc -l)
                FAILS=$(grep -c '</failed>' "$FILENAME" || echo "0")
                EXCEPTIONS=$(grep -c '<exception/>' "$FILENAME" || echo "0")
                echo "[System Test] Queries: $QUERIES; Passes: $PASSES; Fails: $FAILS; EXCEPTIONS: $EXCEPTIONS"
                if [ "$QUERIES" != "$PASSES" ]; then
                    echo "[Alert!] Some system tests have failed. Please try again!"
                    # Please note that we are not failing the build for milestone 2
                    # But before CI/CD submission and M2, need to set this to 2 instead of 0
                    # EXIT_CODE="2"
                    EXIT_CODE="0"
                fi
                fi
            done

            exit $EXIT_CODE

      - name: Upload autotester logs for Milestone 1
        uses: actions/upload-artifact@v2
        with:
          name: autotester-logs
          path: ${{ env.AUTOTESTER_M1_DIR }}/outputs

      - name: Upload autotester logs for Milestone 2
        uses: actions/upload-artifact@v2
        with:
          name: autotester-logs
          path: ${{ env.AUTOTESTER_M2_DIR }}/outputs

      - name: Cleanup Directory
        if: always()
        run: |
          shopt -s dotglob
          rm -rf ./Team19/Code19/build || true

# ai-gen end