name: Build + Autotester (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 09,23 * * *"

env:
    BUILD_TYPE: Debug
    CMAKE_DIR: ${{ github.workspace }}/Team19/Code19
    BUILD_DIR: ${{ github.workspace }}/Team19/Code19/build
    TEST_DIR: ${{ github.workspace }}/Team19/Code19/build/src/autotester
    AUTOTESTER_M1_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m1
    AUTOTESTER_M2_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m2

jobs:
  build_integration_window:
    timeout-minutes: 20
    runs-on: windows-latest
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Build Environment
        shell: bash
        working-directory: ${{ env.CMAKE_DIR }}
        run: cmake -E make_directory build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake -A x64 .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

      - name: Build Project
        shell: bash
        working-directory: ${{ env.BUILD_DIR }}
        run: | 
          cmake --build . --config ${BUILD_TYPE} -j 4
          cmake --build . --target autotester --config ${BUILD_TYPE} -j 4
        
      - name: Run Autotester Tests
        shell: pwsh
        working-directory: ${{ env.AUTOTESTER_M1_DIR }}
        run: |
            mkdir output
            .\window_test.ps1

      - name: Cleanup Directory
        if: always()
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./